/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    caseStudies: CaseStudy;
    media: Media;
    subscribers: Subscriber;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    caseStudies: CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'fr-ca') | ('en' | 'fr-ca')[];
  globals: {
    header: Header;
    footer: Footer;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'fr-ca';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use "home" for the homepage, "about" for the About page.
   */
  slug: string;
  layout?:
    | (
        | HeroBlock
        | StatsBlock
        | DvtaPanelBlock
        | LensesBlock
        | AudienceBlock
        | ComparisonBlock
        | CtaBlock
        | RichTextBlock
      )[]
    | null;
  /**
   * Optional. Overrides the site-wide SEO defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Background tone for this section.
   */
  tone?: ('light' | 'white' | 'dark' | 'graydark') | null;
  eyebrow?: string | null;
  headline: string;
  subhead?: string | null;
  buttons?:
    | {
        link?: {
          label?: string | null;
          type?: ('booking' | 'page' | 'custom') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock".
 */
export interface StatsBlock {
  /**
   * Background tone for this section.
   */
  tone?: ('light' | 'white' | 'dark' | 'graydark') | null;
  eyebrow?: string | null;
  heading?: string | null;
  body?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        source?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DvtaPanelBlock".
 */
export interface DvtaPanelBlock {
  /**
   * Background tone for this section.
   */
  tone?: ('light' | 'white' | 'dark' | 'graydark') | null;
  panelLabel?: string | null;
  tabs?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  scoreCards?:
    | {
        label: string;
        value: number;
        status: 'GREEN' | 'AMBER' | 'CRITICAL';
        id?: string | null;
      }[]
    | null;
  findings?:
    | {
        finding: string;
        lens: string;
        status: 'GREEN' | 'AMBER' | 'CRITICAL';
        id?: string | null;
      }[]
    | null;
  decision?: {
    signal?: string | null;
    text?: string | null;
  };
  heading?: string | null;
  body?: string | null;
  buttons?:
    | {
        link?: {
          label?: string | null;
          type?: ('booking' | 'page' | 'custom') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dvtaPanel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LensesBlock".
 */
export interface LensesBlock {
  /**
   * Background tone for this section.
   */
  tone?: ('light' | 'white' | 'dark' | 'graydark') | null;
  eyebrow?: string | null;
  heading?: string | null;
  body?: string | null;
  lenses?:
    | {
        code: string;
        title: string;
        description: string;
        failurePercent?: string | null;
        failureLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'lenses';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudienceBlock".
 */
export interface AudienceBlock {
  /**
   * Background tone for this section.
   */
  tone?: ('light' | 'white' | 'dark' | 'graydark') | null;
  cards?:
    | {
        eyebrow?: string | null;
        title: string;
        body?: string | null;
        buttons?:
          | {
              link?: {
                label?: string | null;
                type?: ('booking' | 'page' | 'custom') | null;
                page?: (number | null) | Page;
                url?: string | null;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'audience';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonBlock".
 */
export interface ComparisonBlock {
  /**
   * Background tone for this section.
   */
  tone?: ('light' | 'white' | 'dark' | 'graydark') | null;
  eyebrow?: string | null;
  heading?: string | null;
  colTraditional?: string | null;
  colDvta?: string | null;
  rows?:
    | {
        dimension: string;
        traditional: string;
        dvta: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'comparison';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  /**
   * Background tone for this section.
   */
  tone?: ('light' | 'white' | 'dark' | 'graydark') | null;
  eyebrow?: string | null;
  heading?: string | null;
  body?: string | null;
  buttons?:
    | {
        link?: {
          label?: string | null;
          type?: ('booking' | 'page' | 'custom') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  /**
   * Background tone for this section.
   */
  tone?: ('light' | 'white' | 'dark' | 'graydark') | null;
  eyebrow?: string | null;
  heading?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug: string;
  industry?: string | null;
  heroImage?: (number | null) | Media;
  publishedDate?: string | null;
  /**
   * e.g. ~$800K
   */
  ebitdaLabel?: string | null;
  /**
   * e.g. $4M
   */
  askingPriceLabel?: string | null;
  /**
   * Subtitle shown on the index card.
   */
  cardSummary?: string | null;
  /**
   * Drives the badge colour.
   */
  decisionSignal: 'GO' | 'PROCEED_WITH_CONDITIONS' | 'NO_GO';
  /**
   * Display text, e.g. "PROCEED with conditions".
   */
  decisionSignalLabel?: string | null;
  twoViews?: {
    traditional?: string | null;
    dvta?: string | null;
  };
  setup?: string | null;
  surfaced?: {
    intro?: string | null;
    metrics?:
      | {
          label: string;
          value: string;
          note?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  evidence?: string | null;
  decisionImpact?: {
    body?: string | null;
    stats?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  takeaway?: string | null;
  /**
   * Optional. Overrides the site-wide SEO defaults.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  locale?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'caseStudies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        dvtaPanel?: T | DvtaPanelBlockSelect<T>;
        lenses?: T | LensesBlockSelect<T>;
        audience?: T | AudienceBlockSelect<T>;
        comparison?: T | ComparisonBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  tone?: T;
  eyebrow?: T;
  headline?: T;
  subhead?: T;
  buttons?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlock_select".
 */
export interface StatsBlockSelect<T extends boolean = true> {
  tone?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        source?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DvtaPanelBlock_select".
 */
export interface DvtaPanelBlockSelect<T extends boolean = true> {
  tone?: T;
  panelLabel?: T;
  tabs?:
    | T
    | {
        label?: T;
        id?: T;
      };
  scoreCards?:
    | T
    | {
        label?: T;
        value?: T;
        status?: T;
        id?: T;
      };
  findings?:
    | T
    | {
        finding?: T;
        lens?: T;
        status?: T;
        id?: T;
      };
  decision?:
    | T
    | {
        signal?: T;
        text?: T;
      };
  heading?: T;
  body?: T;
  buttons?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LensesBlock_select".
 */
export interface LensesBlockSelect<T extends boolean = true> {
  tone?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  lenses?:
    | T
    | {
        code?: T;
        title?: T;
        description?: T;
        failurePercent?: T;
        failureLabel?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AudienceBlock_select".
 */
export interface AudienceBlockSelect<T extends boolean = true> {
  tone?: T;
  cards?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        body?: T;
        buttons?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ComparisonBlock_select".
 */
export interface ComparisonBlockSelect<T extends boolean = true> {
  tone?: T;
  eyebrow?: T;
  heading?: T;
  colTraditional?: T;
  colDvta?: T;
  rows?:
    | T
    | {
        dimension?: T;
        traditional?: T;
        dvta?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  tone?: T;
  eyebrow?: T;
  heading?: T;
  body?: T;
  buttons?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  tone?: T;
  eyebrow?: T;
  heading?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "caseStudies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  industry?: T;
  heroImage?: T;
  publishedDate?: T;
  ebitdaLabel?: T;
  askingPriceLabel?: T;
  cardSummary?: T;
  decisionSignal?: T;
  decisionSignalLabel?: T;
  twoViews?:
    | T
    | {
        traditional?: T;
        dvta?: T;
      };
  setup?: T;
  surfaced?:
    | T
    | {
        intro?: T;
        metrics?:
          | T
          | {
              label?: T;
              value?: T;
              note?: T;
              id?: T;
            };
      };
  evidence?: T;
  decisionImpact?:
    | T
    | {
        body?: T;
        stats?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  takeaway?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  locale?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navItems?:
    | {
        link?: {
          label?: string | null;
          type?: ('booking' | 'page' | 'custom') | null;
          page?: (number | null) | Page;
          url?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    type?: ('booking' | 'page' | 'custom') | null;
    page?: (number | null) | Page;
    url?: string | null;
    newTab?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  newsletterHeading?: string | null;
  newsletterBody?: string | null;
  newsletterDisclaimer?: string | null;
  socialLinks?:
    | {
        platform: 'LinkedIn' | 'Facebook' | 'Instagram' | 'X' | 'YouTube';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rendered as "© {currentYear} {legalName}".
   */
  legalName?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The single source of truth for every "Book a briefing / Contact" CTA. Use the production portal URL.
   */
  bookingUrl: string;
  siteName?: string | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              url?: T;
              newTab?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        newTab?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  newsletterHeading?: T;
  newsletterBody?: T;
  newsletterDisclaimer?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  legalName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  bookingUrl?: T;
  siteName?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}